### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by isLishude** [isLishude/random.ts#5]
- [x] change api name 2.0 plan
- [x] umd for browser
- [x] push to npm by travis instead of local operation
